// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.
// Filesystem-free public review-state summaries for server descriptors.

export const VALIDATION_REVIEW_STATES = {
  "aa_gradient": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 19,
      "claimsSupported": 19,
      "requiredCases": 12,
      "passedCases": 12,
      "executableClaims": 18,
      "witnessedExecutableClaims": 18
    }
  },
  "abg": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 50,
      "claimsSupported": 50,
      "requiredCases": 40,
      "passedCases": 40,
      "executableClaims": 49,
      "witnessedExecutableClaims": 49
    }
  },
  "anion_gap": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 24,
      "claimsSupported": 24,
      "requiredCases": 14,
      "passedCases": 14,
      "executableClaims": 23,
      "witnessedExecutableClaims": 23
    }
  },
  "apgar": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 25,
      "claimsSupported": 25,
      "requiredCases": 29,
      "passedCases": 29,
      "executableClaims": 24,
      "witnessedExecutableClaims": 24
    }
  },
  "bmi": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 16,
      "claimsSupported": 16,
      "requiredCases": 11,
      "passedCases": 11,
      "executableClaims": 15,
      "witnessedExecutableClaims": 15
    }
  },
  "bsa": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 12,
      "claimsSupported": 12,
      "requiredCases": 10,
      "passedCases": 10,
      "executableClaims": 11,
      "witnessedExecutableClaims": 11
    }
  },
  "bsa_dubois": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 11,
      "claimsSupported": 11,
      "requiredCases": 9,
      "passedCases": 9,
      "executableClaims": 10,
      "witnessedExecutableClaims": 10
    }
  },
  "carboplatin_auc": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 36,
      "claimsSupported": 36,
      "requiredCases": 26,
      "passedCases": 26,
      "executableClaims": 35,
      "witnessedExecutableClaims": 35
    }
  },
  "chadsvasc": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 26,
      "claimsSupported": 26,
      "requiredCases": 23,
      "passedCases": 23,
      "executableClaims": 25,
      "witnessedExecutableClaims": 25
    }
  },
  "chemo_dose_bsa": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 10,
      "passedCases": 10,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "child_pugh": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 23,
      "claimsSupported": 23,
      "requiredCases": 27,
      "passedCases": 27,
      "executableClaims": 22,
      "witnessedExecutableClaims": 22
    }
  },
  "corrected_calcium": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 14,
      "claimsSupported": 14,
      "requiredCases": 11,
      "passedCases": 11,
      "executableClaims": 13,
      "witnessedExecutableClaims": 13
    }
  },
  "creatinine_clearance": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 19,
      "claimsSupported": 19,
      "requiredCases": 13,
      "passedCases": 13,
      "executableClaims": 18,
      "witnessedExecutableClaims": 18
    }
  },
  "csf": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 99,
      "claimsSupported": 99,
      "requiredCases": 46,
      "passedCases": 46,
      "executableClaims": 98,
      "witnessedExecutableClaims": 98
    }
  },
  "eos": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 29,
      "claimsSupported": 29,
      "requiredCases": 12,
      "passedCases": 12,
      "executableClaims": 28,
      "witnessedExecutableClaims": 28
    }
  },
  "free_water_deficit": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 12,
      "passedCases": 12,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "gad7": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 23,
      "claimsSupported": 23,
      "requiredCases": 39,
      "passedCases": 39,
      "executableClaims": 22,
      "witnessedExecutableClaims": 22
    }
  },
  "gcs": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 29,
      "claimsSupported": 29,
      "requiredCases": 45,
      "passedCases": 45,
      "executableClaims": 28,
      "witnessedExecutableClaims": 28
    }
  },
  "gfr": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 26,
      "passedCases": 26,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "gir": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 15,
      "claimsSupported": 15,
      "requiredCases": 12,
      "passedCases": 12,
      "executableClaims": 14,
      "witnessedExecutableClaims": 14
    }
  },
  "grace": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 29,
      "claimsSupported": 29,
      "requiredCases": 20,
      "passedCases": 20,
      "executableClaims": 28,
      "witnessedExecutableClaims": 28
    }
  },
  "hepb": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 26,
      "claimsSupported": 26,
      "requiredCases": 282,
      "passedCases": 282,
      "executableClaims": 25,
      "witnessedExecutableClaims": 25
    }
  },
  "ibw": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 10,
      "claimsSupported": 10,
      "requiredCases": 8,
      "passedCases": 8,
      "executableClaims": 9,
      "witnessedExecutableClaims": 9
    }
  },
  "ich_volume": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 19,
      "claimsSupported": 19,
      "requiredCases": 12,
      "passedCases": 12,
      "executableClaims": 18,
      "witnessedExecutableClaims": 18
    }
  },
  "kdpi": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 30,
      "claimsSupported": 30,
      "requiredCases": 18,
      "passedCases": 18,
      "executableClaims": 29,
      "witnessedExecutableClaims": 29
    }
  },
  "map": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 14,
      "claimsSupported": 14,
      "requiredCases": 11,
      "passedCases": 11,
      "executableClaims": 13,
      "witnessedExecutableClaims": 13
    }
  },
  "meld": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 41,
      "claimsSupported": 41,
      "requiredCases": 29,
      "passedCases": 29,
      "executableClaims": 40,
      "witnessedExecutableClaims": 40
    }
  },
  "mews": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 21,
      "claimsSupported": 21,
      "requiredCases": 34,
      "passedCases": 34,
      "executableClaims": 20,
      "witnessedExecutableClaims": 20
    }
  },
  "morse_fall_scale": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 22,
      "passedCases": 22,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "neonatal_measurements": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 30,
      "claimsSupported": 30,
      "requiredCases": 25,
      "passedCases": 25,
      "executableClaims": 29,
      "witnessedExecutableClaims": 29
    }
  },
  "nihss": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 50,
      "claimsSupported": 50,
      "requiredCases": 107,
      "passedCases": 107,
      "executableClaims": 49,
      "witnessedExecutableClaims": 49
    }
  },
  "oxygenation_index": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 22,
      "claimsSupported": 22,
      "requiredCases": 18,
      "passedCases": 18,
      "executableClaims": 21,
      "witnessedExecutableClaims": 21
    }
  },
  "pews": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 13,
      "claimsSupported": 13,
      "requiredCases": 24,
      "passedCases": 24,
      "executableClaims": 12,
      "witnessedExecutableClaims": 12
    }
  },
  "qsofa": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 14,
      "claimsSupported": 14,
      "requiredCases": 17,
      "passedCases": 17,
      "executableClaims": 13,
      "witnessedExecutableClaims": 13
    }
  },
  "r_factor": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 15,
      "passedCases": 15,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "ranson": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 78,
      "claimsSupported": 78,
      "requiredCases": 74,
      "passedCases": 74,
      "executableClaims": 77,
      "witnessedExecutableClaims": 77
    }
  },
  "sodium_deficit": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 24,
      "claimsSupported": 24,
      "requiredCases": 14,
      "passedCases": 14,
      "executableClaims": 23,
      "witnessedExecutableClaims": 23
    }
  },
  "timi": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 20,
      "claimsSupported": 20,
      "requiredCases": 17,
      "passedCases": 17,
      "executableClaims": 19,
      "witnessedExecutableClaims": 19
    }
  },
  "wells_dvt": {
    "state": "scenario_verified",
    "blockerCodes": [],
    "counts": {
      "claimsTotal": 18,
      "claimsSupported": 18,
      "requiredCases": 18,
      "passedCases": 18,
      "executableClaims": 17,
      "witnessedExecutableClaims": 17
    }
  }
} as const;
