/**
 * Guards the Workers deployment path:
 *  - the bundled `spec-data.generated.ts` must not drift from `specs/*.yaml`
 *    (it is regenerated by `npm run gen:specs`, but a manual spec edit without
 *    a rebuild would silently ship stale specs to the remote server);
 *  - priming from those bundled texts must yield the same catalog as the disk
 *    load, proving the fs-free Workers path is equivalent to the Node path.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { loadSpecs, primeSpecs } from '../engine/index.js';
import { SPEC_TEXTS, PKG_VERSION } from './spec-data.generated.js';
import worker from './worker.js';

const SPECS_DIR = join(dirname(fileURLToPath(import.meta.url)), '../../specs');
const WRANGLER_CONFIG = join(SPECS_DIR, '../wrangler.jsonc');
const LEGACY_PROTOCOL_VERSION = '2025-11-25';

describe('spec-data.generated.ts', () => {
  it('matches specs/*.yaml exactly (run `npm run gen:specs` if this fails)', () => {
    const onDisk: Record<string, string> = {};
    for (const f of readdirSync(SPECS_DIR).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))) {
      onDisk[f] = readFileSync(join(SPECS_DIR, f), 'utf8');
    }
    expect(SPEC_TEXTS).toEqual(onDisk);
  });

  it('has the package version', () => {
    const version = (
      JSON.parse(readFileSync(join(SPECS_DIR, '../package.json'), 'utf8')) as { version: string }
    ).version;
    expect(PKG_VERSION).toBe(version);
  });

  it('primes the same catalog as the disk load', () => {
    const fromDisk = [...loadSpecs().keys()].sort();
    primeSpecs(SPEC_TEXTS);
    const fromBundle = [...loadSpecs().keys()].sort();
    expect(fromBundle).toEqual(fromDisk);
  });
});

const initializeBody = JSON.stringify({
  jsonrpc: '2.0',
  id: 1,
  method: 'initialize',
  params: {
    protocolVersion: LEGACY_PROTOCOL_VERSION,
    capabilities: {},
    clientInfo: { name: 'worker-test', version: '0.0.0' },
  },
});

describe('Worker Streamable HTTP transport', () => {
  it('redirects plaintext requests and applies HSTS to every HTTPS response', async () => {
    const redirected = await worker.fetch(new Request('http://worker.example/mcp?probe=1'));
    expect(redirected.status).toBe(308);
    expect(redirected.headers.get('location')).toBe('https://worker.example/mcp?probe=1');

    for (const path of ['/', '/health', '/wrong', '/responsible-use', '/.well-known/openai-apps-challenge']) {
      const response = await worker.fetch(new Request(`https://worker.example${path}`));
      expect(response.headers.get('strict-transport-security'), path)
        .toBe('max-age=31536000; includeSubDomains');
      expect(response.headers.get('x-content-type-options'), path).toBe('nosniff');
    }
  });

  it('keeps wrong-path and stateless method behavior explicit', async () => {
    expect((await worker.fetch(new Request('https://worker.example/wrong'))).status).toBe(404);
    for (const method of ['GET', 'DELETE', 'PUT', 'PATCH']) {
      const response = await worker.fetch(new Request('https://worker.example/mcp', { method }));
      expect(response.status, method).toBe(405);
      expect(response.headers.get('allow'), method).toBe('POST');
      expect(response.headers.get('content-type'), method).toBe('application/json');
      expect(response.headers.get('cache-control'), method).toBe('no-store');
      expect(await response.json(), method).toMatchObject({ error: { code: -32000 }, id: null });
    }
  });

  it('routes humans to documentation and publishes health metadata and Responsible Use', async () => {
    for (const method of ['GET', 'HEAD']) {
      const root = await worker.fetch(new Request('https://worker.example/', { method }));
      expect(root.status, method).toBe(308);
      expect(root.headers.get('location'), method).toBe('https://mcp.oath.md/docs/');
    }

    const health = await worker.fetch(new Request('https://worker.example/health'));
    expect(health.status).toBe(200);
    await expect(health.json()).resolves.toMatchObject({
      name: 'oath-mcp',
      version: PKG_VERSION,
      endpoint: '/mcp',
      documentation: 'https://mcp.oath.md/docs/',
      responsibleUse: '/responsible-use',
      openAIAppsChallenge: '/.well-known/openai-apps-challenge',
    });

    const notice = await worker.fetch(new Request('https://worker.example/responsible-use'));
    expect(notice.status).toBe(200);
    expect(notice.headers.get('content-type')).toBe('text/markdown; charset=UTF-8');
    expect(await notice.text()).toContain('# Responsible Use');
  });

  it('serves only the configured OpenAI app-verification token', async () => {
    const url = 'https://worker.example/.well-known/openai-apps-challenge';
    const missing = await worker.fetch(new Request(url));
    expect(missing.status).toBe(404);

    const configured = await worker.fetch(new Request(url), {
      OPENAI_APPS_CHALLENGE: 'portal-generated-token',
    });
    expect(configured.status).toBe(200);
    expect(configured.headers.get('content-type')).toBe('text/plain; charset=UTF-8');
    expect(configured.headers.get('cache-control')).toBe('no-store');
    expect(await configured.text()).toBe('portal-generated-token');
  });

  it('allows absent and configured Origins but rejects every other browser Origin', async () => {
    const request = (origin?: string) => new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
        ...(origin ? { origin } : {}),
      },
      body: initializeBody,
    });

    const noOrigin = await worker.fetch(request());
    const allowed = await worker.fetch(request('https://app.example'), {
      OATH_ALLOWED_ORIGINS: 'https://app.example',
    });
    expect(noOrigin.status).toBe(200);
    expect(allowed.status).toBe(200);
    expect(noOrigin.headers.get('content-type')).toBe('application/json');
    expect(allowed.headers.get('content-type')).toBe('application/json');
    expect(noOrigin.headers.get('cache-control')).toBe('no-store');
    expect(allowed.headers.get('access-control-allow-origin')).toBe('https://app.example');
    const hostile = await worker.fetch(request('https://evil.example'), {
      OATH_ALLOWED_ORIGINS: 'https://app.example',
    });
    expect(hostile.status).toBe(403);
    expect(hostile.headers.get('content-type')).toBe('text/plain; charset=UTF-8');
    expect(await hostile.text()).toBe('Forbidden origin.');

    const preflight = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'OPTIONS',
      headers: { origin: 'https://app.example' },
    }), { OATH_ALLOWED_ORIGINS: 'https://app.example' });
    expect(preflight.status).toBe(204);
    expect(preflight.headers.get('access-control-allow-origin')).toBe('https://app.example');
    expect(preflight.headers.get('access-control-allow-methods')).toContain('POST');
  });

  it('accepts the checked-in production documentation origin', async () => {
    const config = readFileSync(WRANGLER_CONFIG, 'utf8');
    const configuredOrigins = /"OATH_ALLOWED_ORIGINS"\s*:\s*"([^"]+)"/.exec(config)?.[1];
    expect(configuredOrigins).toBe('https://oath.md,https://mcp.oath.md');
    const origin = 'https://mcp.oath.md';
    const response = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
        origin,
      },
      body: initializeBody,
    }), { OATH_ALLOWED_ORIGINS: configuredOrigins });
    expect(response.status).toBe(200);
    expect(response.headers.get('access-control-allow-origin')).toBe(origin);
  });

  it('returns a sanitized 429 when the configured edge limiter rejects a client', async () => {
    const response = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
        'cf-connecting-ip': '192.0.2.1',
      },
      body: initializeBody,
    }), {
      OATH_RATE_LIMITER: { limit: async () => ({ success: false }) },
    });
    expect(response.status).toBe(429);
    expect(response.headers.get('retry-after')).toBe('60');
    await expect(response.json()).resolves.toMatchObject({
      error: { message: 'Rate limit exceeded.' },
      id: null,
    });
  });

  it('sanitizes infrastructure failures without echoing request data', async () => {
    const response = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: '{"private":"patient-name"}',
    }));
    expect(response.status).toBeGreaterThanOrEqual(400);
    expect(await response.text()).not.toContain('patient-name');
  });

  it('rejects JSON-RPC batches and oversized requests before transport dispatch', async () => {
    for (const body of ['[]', `[${initializeBody}]`]) {
      const response = await worker.fetch(new Request('https://worker.example/mcp', {
        method: 'POST',
        headers: {
          accept: 'application/json, text/event-stream',
          'content-type': 'application/json',
        },
        body,
      }));
      expect(response.status, body).toBe(400);
      await expect(response.json()).resolves.toMatchObject({
        error: { code: -32600, message: expect.stringContaining('batches') },
        id: null,
      });
    }

    const oversized = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
      },
      body: JSON.stringify({ payload: 'x'.repeat(101 * 1024) }),
    }));
    expect(oversized.status).toBe(413);
    await expect(oversized.json()).resolves.toMatchObject({
      error: { code: -32600, message: 'Request body too large.' },
    });
  });

  it('cancels a chunked request as soon as its streamed body crosses the limit', async () => {
    const chunk = new Uint8Array(4 * 1024).fill(0x78);
    let pulls = 0;
    let cancelled = false;
    const body = new ReadableStream<Uint8Array>({
      pull(controller) {
        pulls += 1;
        if (pulls > 300) {
          controller.close();
          return;
        }
        controller.enqueue(chunk.slice());
      },
      cancel() {
        cancelled = true;
      },
    });
    const init = {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
      },
      body,
      duplex: 'half',
    } satisfies RequestInit & { duplex: 'half' };

    const response = await worker.fetch(new Request('https://worker.example/mcp', init));

    expect(response.status).toBe(413);
    expect(cancelled).toBe(true);
    expect(pulls).toBeLessThan(40);
    await expect(response.json()).resolves.toMatchObject({
      error: { code: -32600, message: 'Request body too large.' },
    });
  });

  it('rejects unsupported headers before pulling a request body', async () => {
    const headerCases: { headers: Record<string, string>; status: number }[] = [
      { headers: { 'content-type': 'application/json' }, status: 406 },
      { headers: { accept: 'application/json, text/event-stream', 'content-type': 'text/plain' }, status: 415 },
      { headers: { accept: 'application/jsonp, text/event-streaming', 'content-type': 'application/json' }, status: 406 },
      { headers: { accept: 'application/json, text/event-stream', 'content-type': 'application/jsonp' }, status: 415 },
      {
        headers: { accept: 'application/json, text/event-stream', 'content-type': 'application/json; charset=iso-8859-1' },
        status: 415,
      },
      { headers: {
        accept: 'application/json, text/event-stream',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
      }, status: 415 },
    ];
    for (const { headers, status } of headerCases) {
      let pulls = 0;
      const body = new ReadableStream<Uint8Array>({
        pull(controller) {
          pulls += 1;
          controller.enqueue(new Uint8Array([0x7b]));
        },
      }, { highWaterMark: 0 });
      const init = {
        method: 'POST', headers, body, duplex: 'half',
      } satisfies RequestInit & { duplex: 'half' };

      const response = await worker.fetch(new Request('https://worker.example/mcp', init));

      expect(response.status).toBe(status);
      expect(pulls).toBe(0);
      if (status === 415) {
        await expect(response.clone().json()).resolves.toMatchObject({
          error: { message: expect.stringContaining('UTF-8') },
        });
      }
      await body.cancel();
    }
  });

  it('distinguishes malformed JSON from a valid but invalid JSON-RPC request', async () => {
    const request = (body: BodyInit) => worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST',
      headers: {
        accept: 'application/json, text/event-stream',
        'content-type': 'application/json',
      },
      body,
    }));

    for (const body of ['{}', 'null', '42', '{"jsonrpc":"2.0","id":1,"method":42}']) {
      const response = await request(body);
      expect(response.status, body).toBe(400);
      await expect(response.json()).resolves.toMatchObject({ error: { code: -32600 } });
    }
    const malformed = await request('{bad');
    expect(malformed.status).toBe(400);
    await expect(malformed.json()).resolves.toMatchObject({ error: { code: -32700 } });

    const empty = await request('');
    expect(empty.status).toBe(400);
    await expect(empty.json()).resolves.toMatchObject({ error: { code: -32700 } });

    const invalidUtf8 = await request(new Uint8Array([0xc3, 0x28]));
    expect(invalidUtf8.status).toBe(400);
    await expect(invalidUtf8.json()).resolves.toMatchObject({ error: { code: -32700 } });
  });

  it('accepts the exact byte limit and counts multibyte request bytes correctly', async () => {
    const shellBytes = new TextEncoder().encode('{"payload":""}').byteLength;
    const exactBody = `{"payload":"${'x'.repeat(100 * 1024 - shellBytes)}"}`;
    expect(new TextEncoder().encode(exactBody)).toHaveLength(100 * 1024);
    const headers = {
      accept: 'application/json, text/event-stream',
      'content-type': 'application/json',
    };

    const exact = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST', headers, body: exactBody,
    }));
    expect(exact.status).toBe(400);
    await expect(exact.json()).resolves.toMatchObject({ error: { code: -32600 } });

    const multibyte = JSON.stringify({ payload: '🩺'.repeat(30 * 1024) });
    expect(multibyte.length).toBeLessThan(100 * 1024);
    expect(new TextEncoder().encode(multibyte).byteLength).toBeGreaterThan(100 * 1024);
    const oversized = await worker.fetch(new Request('https://worker.example/mcp', {
      method: 'POST', headers, body: multibyte,
    }));
    expect(oversized.status).toBe(413);
  });
});
