/**
 * `bundle-specs` — emit `src/server/spec-data.generated.ts` holding every
 * `specs/*.yaml` as a string plus the package version. The Cloudflare Worker
 * entry has no filesystem, so it primes the engine from this module instead of
 * reading `specs/` at runtime (Node entries keep reading from disk).
 *
 * Runs via `npm run gen:specs` and automatically before `npm run build`.
 * `src/server/worker.test.ts` fails if the generated file drifts from `specs/`.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { validateSpecTexts } from '../engine/load-specs.js';
import type { CalcSpec, InputSpec, OutputSpec } from '../engine/spec-schema.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
export const GENERATED_ARTIFACT_PATHS = {
  specData: 'src/server/spec-data.generated.ts',
  responsibleUse: 'src/server/responsible-use.generated.ts',
  computeIndex: 'src/compute/index.generated.ts',
  computeTypes: 'src/compute/types.generated.ts',
  validationState: 'src/server/validation-state.generated.ts',
} as const;
const SPEC_OUT_PATH = join(ROOT, GENERATED_ARTIFACT_PATHS.specData);
const RESPONSIBLE_USE_OUT_PATH = join(ROOT, GENERATED_ARTIFACT_PATHS.responsibleUse);
const COMPUTE_OUT_PATH = join(ROOT, GENERATED_ARTIFACT_PATHS.computeIndex);
const TYPES_OUT_PATH = join(ROOT, GENERATED_ARTIFACT_PATHS.computeTypes);
const VALIDATION_STATE_OUT_PATH = join(ROOT, GENERATED_ARTIFACT_PATHS.validationState);

function outputIsCurrent(path: string, expected: string): boolean {
  return existsSync(path) && readFileSync(path, 'utf8') === expected;
}

export async function bundleSpecs(argv: string[]): Promise<number> {
  const check = argv.includes('--check');
  const specsDir = join(ROOT, 'specs');
  const files = readdirSync(specsDir)
    .filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
    .sort();
  const version = (
    JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { version: string }
  ).version;
  const texts = Object.fromEntries(files.map((file) => [file, readFileSync(join(specsDir, file), 'utf8')]));
  const responsibleUseText = readFileSync(join(ROOT, 'docs/RESPONSIBLE_USE.md'), 'utf8');
  const specs = [...validateSpecTexts(texts).values()];

  const entries = files.map(
    (file) => `  ${JSON.stringify(file)}: ${JSON.stringify(texts[file])},`,
  );
  const bundledSpecs = [
    '// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.',
    '// Bundled copies of specs/*.yaml for runtimes with no filesystem (Workers).',
    '',
    `export const PKG_VERSION = ${JSON.stringify(version)};`,
    '',
    'export const SPEC_TEXTS: Record<string, string> = {',
    ...entries,
    '};',
    '',
  ].join('\n');

  const bundledResponsibleUse = [
    '// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.',
    '// Bundled copy of docs/RESPONSIBLE_USE.md for filesystem-free runtimes.',
    '',
    `export const RESPONSIBLE_USE_TEXT = ${JSON.stringify(responsibleUseText)};`,
    '',
  ].join('\n');

  const computeIndex = [
    '// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.',
    '// Registers exactly one compute module for every declarative spec.',
    '',
    ...files.map((file) => `import './${file.replace(/\.ya?ml$/, '')}.js';`),
    '',
  ].join('\n');

  const inputType = (input: InputSpec): string => {
    switch (input.kind) {
      case 'number':
      case 'integer':
      case 'quantity':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'enum':
        return input.enumValues.map((option) => JSON.stringify(option.value)).join(' | ');
    }
  };
  const outputType = (output: OutputSpec): string => {
    switch (output.kind) {
      case 'number':
      case 'integer':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'string':
      case 'enum':
        return output.kind === 'enum'
          ? output.allowedValues.map((value) => JSON.stringify(value)).join(' | ')
          : 'string';
      case 'string_list':
        return 'string[]';
      case 'number_list':
        return 'number[]';
      case 'number_range':
        return '{ low: number; high: number; mean?: number }';
      case 'criterion_list':
        return 'CriterionProvenance[]';
    }
  };
  const mapEntries = <T>(
    spec: CalcSpec,
    values: Record<string, T>,
    typeFor: (value: T) => string,
    optional: (value: T) => boolean,
  ): string[] => [
    `  ${JSON.stringify(spec.id)}: {`,
    ...Object.entries(values).map(
      ([name, value]) => `    ${JSON.stringify(name)}${optional(value) ? '?' : ''}: ${typeFor(value)};`,
    ),
    '  };',
  ];
  const generatedTypes = [
    '// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.',
    '// Exact normalized compute contracts derived from specs/*.yaml.',
    '',
    `export type CalculatorId = ${specs.map((spec) => JSON.stringify(spec.id)).join(' | ')};`,
    '',
    "export type CriterionState = 'met' | 'not_met' | 'unknown' | 'not_due' | 'not_applicable';",
    'export interface CriterionProvenance {',
    '  criterion: string;',
    '  state: CriterionState;',
    '  points?: number;',
    '  observedInputs: string[];',
    '  rationale: string;',
    '}',
    '',
    'export interface CalculatorInputsById {',
    ...specs.flatMap((spec) =>
      mapEntries(
        spec,
        spec.inputs,
        inputType,
        (input) => !input.required && input.default === undefined,
      ),
    ),
    '}',
    '',
    'export interface CalculatorOutputsById {',
    ...specs.flatMap((spec) =>
      mapEntries(
        spec,
        spec.outputs,
        outputType,
        (output) => output.availability.kind !== 'always',
      ),
    ),
    '}',
    '',
    'export type ComputeValue =',
    '  | number | string | boolean | string[] | number[]',
    '  | { low: number; high: number; mean?: number } | CriterionProvenance[];',
    '',
  ].join('\n');

  const structuralArtifacts = [
    [SPEC_OUT_PATH, bundledSpecs, 'src/server/spec-data.generated.ts'],
    [RESPONSIBLE_USE_OUT_PATH, bundledResponsibleUse, 'src/server/responsible-use.generated.ts'],
    [COMPUTE_OUT_PATH, computeIndex, 'src/compute/index.generated.ts'],
    [TYPES_OUT_PATH, generatedTypes, 'src/compute/types.generated.ts'],
  ] as const;

  // The runtime case runner imports the generated compute index and exact
  // types. Write those structural artifacts first so a prospective catalog can
  // register and compile a newly added calculator while deriving its review
  // state. In check mode, fail before importing runtime code if they drift.
  if (check) {
    const stale = structuralArtifacts.filter(([path, expected]) => !outputIsCurrent(path, expected));
    if (stale.length > 0) {
      process.stderr.write(
        `Generated files are stale: ${stale.map(([, , label]) => label).join(', ')}\nRun npm run gen:specs.\n`,
      );
      return 1;
    }
  } else {
    for (const [path, content] of structuralArtifacts) writeFileSync(path, content);
    const provisionalStates = Object.fromEntries(specs.map((spec) => [spec.id, {
      state: 'blocked',
      blockerCodes: ['generation.review_state_pending'],
      counts: {
        claimsTotal: 0,
        claimsSupported: 0,
        requiredCases: 0,
        passedCases: 0,
        executableClaims: 0,
        witnessedExecutableClaims: 0,
      },
    }]));
    writeFileSync(VALIDATION_STATE_OUT_PATH, [
      '// GENERATED provisionally by `npm run gen:specs` while review states are derived.',
      '// A failed generation stays truthfully blocked and is rejected by check:generated.',
      '',
      `export const VALIDATION_REVIEW_STATES = ${JSON.stringify(provisionalStates, null, 2)} as const;`,
      '',
    ].join('\n'));
  }

  // Derive public review states from real case execution, never from authored
  // booleans or an empty result map. Dynamic imports avoid pulling the MCP
  // boundary into callers that only import this module for its types.
  const [{ createValidationCaseRunner }, { validateClinicalCatalog }] = await Promise.all([
    import('../server/validation-case-runner.js'),
    import('../validation/index.js'),
  ]);
  const caseRunner = await createValidationCaseRunner();
  let clinicalReport: Awaited<ReturnType<typeof validateClinicalCatalog>>;
  try {
    clinicalReport = await validateClinicalCatalog({ caseRunner });
  } finally {
    await caseRunner.close();
  }
  const statesById = new Map(
    clinicalReport.calculatorReports.map((report) => [report.calculatorId, report.reviewState]),
  );
  const validationStates = Object.fromEntries(specs.map((spec) => {
    const state = statesById.get(spec.id);
    if (state === undefined) {
      const reported = clinicalReport.calculatorReports.map((report) => report.calculatorId).sort();
      const relatedErrors = clinicalReport.errors
        .filter((issue) => issue.calculatorId === spec.id)
        .map((issue) => `${issue.code}: ${issue.message}`);
      throw new Error(
        `Missing derived validation review state for '${spec.id}'. ` +
        `Reported calculators: ${reported.join(', ') || '(none)'}. ` +
        `Related validation errors: ${relatedErrors.join('; ') || '(none)'}.`,
      );
    }
    return [spec.id, {
      state: state.state,
      blockerCodes: [...new Set(state.blockers.map((blocker) => blocker.code))].sort(),
      counts: state.counts,
    }];
  }));
  const generatedValidationStates = [
    '// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.',
    '// Filesystem-free public review-state summaries for server descriptors.',
    '',
    `export const VALIDATION_REVIEW_STATES = ${JSON.stringify(validationStates, null, 2)} as const;`,
    '',
  ].join('\n');

  if (check) {
    const stale = [
      [VALIDATION_STATE_OUT_PATH, generatedValidationStates, 'src/server/validation-state.generated.ts'],
    ].filter(([path, expected]) => !outputIsCurrent(path, expected));
    if (stale.length > 0) {
      process.stderr.write(
        `Generated files are stale: ${stale.map(([, , label]) => label).join(', ')}\nRun npm run gen:specs.\n`,
      );
      return 1;
    }
    process.stdout.write(`Generated spec artifacts are current (${files.length} specs).\n`);
    return 0;
  }

  writeFileSync(VALIDATION_STATE_OUT_PATH, generatedValidationStates);
  process.stdout.write(
    `Wrote generated spec data, Responsible Use notice, compute index, compute types, and validation states (${files.length} specs, v${version})\n`,
  );
  return 0;
}
