// GENERATED by `npm run gen:specs` (src/cli/bundle-specs.ts) — do not edit.
// Exact normalized compute contracts derived from specs/*.yaml.

export type CalculatorId = "aa_gradient" | "abg" | "anion_gap" | "apgar" | "bmi" | "bsa" | "bsa_dubois" | "carboplatin_auc" | "chadsvasc" | "chemo_dose_bsa" | "child_pugh" | "corrected_calcium" | "creatinine_clearance" | "csf" | "eos" | "free_water_deficit" | "gad7" | "gcs" | "gfr" | "gir" | "grace" | "hepb" | "ibw" | "ich_volume" | "kdpi" | "map" | "meld" | "mews" | "morse_fall_scale" | "neonatal_measurements" | "nihss" | "oxygenation_index" | "pews" | "qsofa" | "r_factor" | "ranson" | "sodium_deficit" | "timi" | "wells_dvt";

export type CriterionState = 'met' | 'not_met' | 'unknown' | 'not_due' | 'not_applicable';
export interface CriterionProvenance {
  criterion: string;
  state: CriterionState;
  points?: number;
  observedInputs: string[];
  rationale: string;
}

export interface CalculatorInputsById {
  "aa_gradient": {
    "pao2": number;
    "paco2": number;
    "fio2": number;
    "age": number;
    "altitude": number;
  };
  "abg": {
    "ph": number;
    "paco2": number;
    "bicarbonate": number;
    "sodium": number;
    "chloride": number;
    "albumin"?: number;
    "sample_type"?: "arterial" | "peripheral_venous";
    "venous_sample"?: boolean;
  };
  "anion_gap": {
    "sodium": number;
    "chloride": number;
    "bicarbonate": number;
    "albumin"?: number;
  };
  "apgar": {
    "assessment_minute": "minute_1" | "minute_5" | "minute_10" | "minute_15" | "minute_20";
    "oxygen": boolean;
    "ppv_or_ncpap": boolean;
    "endotracheal_tube": boolean;
    "chest_compressions": boolean;
    "epinephrine": boolean;
    "appearance": "blue_or_pale" | "body_pink_extremities_blue" | "pink_all_over";
    "pulse": "absent" | "less_than_100" | "at_least_100";
    "grimace": "no_response" | "grimace" | "cough_sneeze_cry";
    "activity": "limp" | "some_flexion" | "active_motion";
    "respiratory": "absent" | "weak_or_irregular" | "strong_cry";
  };
  "bmi": {
    "weight_kg": number;
    "height_cm": number;
  };
  "bsa": {
    "weight_kg": number;
    "height_cm": number;
  };
  "bsa_dubois": {
    "height_cm": number;
    "weight_kg": number;
  };
  "carboplatin_auc": {
    "target_auc": number;
    "gfr": number;
    "kidney_function_method": "measured_gfr" | "ckd_epi_2009_no_race_egfr" | "cockcroft_gault_crcl";
    "kidney_function_indexing": "absolute_ml_min" | "indexed_ml_min_1_73m2";
    "patient_bsa"?: number;
    "treatment_intent": "curative" | "non_curative" | "unspecified";
    "cap_policy": "no_cap_addikd_2022" | "nci_ctep_estimated_125";
    "rounding_policy": "nearest_whole_mg_addikd_2022";
  };
  "chadsvasc": {
    "age_group": "under_65" | "age_65_74" | "age_75_plus";
    "sex": "male" | "female";
    "chf": boolean;
    "hypertension": boolean;
    "stroke_history": boolean;
    "vascular_disease": boolean;
    "diabetes": boolean;
  };
  "chemo_dose_bsa": {
    "dose_per_m2": number;
    "bsa": number;
    "dose_reduction": number;
    "cap_bsa": boolean;
  };
  "child_pugh": {
    "bilirubin_category": "low" | "moderate" | "high";
    "albumin_category": "high" | "moderate" | "low";
    "inr_category": "low" | "moderate" | "high";
    "ascites": "none" | "mild" | "moderate";
    "encephalopathy": "none" | "mild" | "severe";
  };
  "corrected_calcium": {
    "calcium": number;
    "albumin": number;
  };
  "creatinine_clearance": {
    "age": number;
    "weight_kg": number;
    "creatinine": number;
    "sex": "male" | "female";
  };
  "csf": {
    "age_years": number;
    "wbc_per_ul": number;
    "wbc_diff": "pmn" | "lymphocyte" | "mixed" | "unknown";
    "rbc_per_ul"?: number;
    "traumatic_tap_method": "none" | "one_wbc_per_500_rbc" | "one_wbc_per_1000_rbc" | "one_wbc_per_1500_rbc";
    "appearance"?: "clear" | "cloudy" | "bloody" | "xanthochromic" | "unknown";
    "opening_pressure_cm_h2o"?: number;
    "csf_glucose_mmol_l"?: number;
    "serum_glucose_mmol_l"?: number;
    "protein_mg_dl"?: number;
    "gram_stain_result": "positive" | "negative" | "unknown" | "not_tested";
    "bacterial_culture_result": "positive" | "negative" | "unknown" | "not_tested";
    "pathogen_pcr_result": "positive" | "negative" | "unknown" | "not_tested";
    "pathogen_pcr_identity"?: "hsv1" | "hsv2" | "vzv" | "enterovirus" | "bacterial_panel" | "other" | "not_specified";
    "mycobacterial_result": "positive" | "negative" | "unknown" | "not_tested";
    "mycobacterial_assay"?: "smear" | "culture" | "pcr" | "other" | "not_specified";
    "fungal_result": "positive" | "negative" | "unknown" | "not_tested";
    "fungal_assay"?: "cryptococcal_antigen" | "india_ink" | "beta_d_glucan" | "culture" | "other" | "not_specified";
    "oligoclonal_band_status": "csf_restricted" | "matched_serum_and_csf" | "absent" | "unknown" | "not_tested";
    "neural_antibody_result": "positive" | "negative" | "unknown" | "not_tested";
    "neural_antibody_identity"?: "nmda_receptor" | "lgi1" | "caspr2" | "gaba_b" | "ampa" | "other" | "not_specified";
    "neural_antibody_specimen"?: "csf" | "serum" | "paired" | "not_specified";
    "symptom_onset_days"?: number;
    "antimicrobial_pretreatment": "yes" | "no" | "unknown";
    "immune_status": "immunocompetent" | "immunocompromised" | "unknown";
    "imaging_context": "normal_or_no_explanation" | "supports_sah" | "other_abnormality" | "not_done" | "unknown";
    "xanthochromia_method": "spectrophotometry" | "visual" | "not_tested" | "unknown";
    "xanthochromia_result": "positive" | "negative" | "unknown" | "not_tested";
    "hours_from_onset_to_lumbar_puncture"?: number;
  };
  "eos": {
    "model_version": "updated_2024_universal_gbs" | "original_2017_nonuniversal_gbs";
    "baseline_incidence": "0.1" | "0.2" | "0.3" | "0.4" | "0.5" | "0.6" | "0.7" | "0.8" | "0.9" | "1" | "2" | "4";
    "temperature": number;
    "rom_hours": number;
    "gestational_age": number;
    "antibiotic_status": "none" | "gbs_specific_ge_2h_or_any_2_to_4h" | "broad_spectrum_ge_4h";
    "gbs_status": "positive" | "negative" | "unknown";
    "clinical_appearance": "well_appearing" | "equivocal" | "clinical_illness";
  };
  "free_water_deficit": {
    "weight_kg": number;
    "current_sodium": number;
    "ideal_sodium": number;
    "patient_category": "adult_male" | "adult_female" | "elderly_male" | "elderly_female";
  };
  "gad7": {
    "feeling_nervous": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "cannot_control_worrying": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "worrying_too_much": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "trouble_relaxing": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "restlessness": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "easily_annoyed": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
    "feeling_afraid": "not_at_all" | "several_days" | "more_than_half_the_days" | "nearly_every_day";
  };
  "gcs": {
    "assessment_context": "general_consciousness" | "acute_brain_injury" | "traumatic_brain_injury";
    "modifier_context": "none" | "intubation_or_tracheostomy" | "sedation" | "paralysis" | "language_or_communication_barrier" | "ocular_obstruction" | "other" | "multiple_modifiers";
    "eye_opening": "none" | "to_pain" | "to_speech" | "spontaneous" | "not_testable_ocular_obstruction";
    "verbal_response": "none" | "incomprehensible_sounds" | "inappropriate_words" | "confused" | "oriented" | "not_testable_intubation" | "not_testable_communication_barrier";
    "motor_response": "none" | "extension" | "flexion" | "flexion_withdrawal" | "localizes_to_pain" | "obeys_commands" | "not_testable_paralysis";
  };
  "gfr": {
    "creatinine": number;
    "age": number;
    "sex": "male" | "female";
  };
  "gir": {
    "weight_kg": number;
    "dextrose_concentration": number;
    "infusion_rate": number;
  };
  "grace": {
    "age": number;
    "heart_rate": number;
    "systolic_bp": number;
    "creatinine": number;
    "killip_class": "i" | "ii" | "iii" | "iv";
    "cardiac_arrest": boolean;
    "st_segment_deviation": boolean;
    "elevated_cardiac_enzymes": boolean;
  };
  "hepb": {
    "hbsag": "positive" | "negative" | "unknown" | "not_tested";
    "anti_hbc": "positive" | "negative" | "unknown" | "not_tested";
    "anti_hbs": "positive" | "negative" | "unknown" | "not_tested";
    "igm_anti_hbc": "positive" | "negative" | "unknown" | "not_tested";
    "hbeag": "positive" | "negative" | "unknown" | "not_tested";
    "anti_hbe": "positive" | "negative" | "unknown" | "not_tested";
  };
  "ibw": {
    "height_cm": number;
    "sex": "male" | "female";
  };
  "ich_volume": {
    "length_cm": number;
    "width_cm": number;
    "slice_width_cm": number;
    "num_slices": number;
    "ellipsoid_shape": boolean;
  };
  "kdpi": {
    "donor_age_years": number;
    "donor_height_cm": number;
    "donor_weight_kg": number;
    "donor_hypertension": boolean;
    "donor_diabetes": boolean;
    "cause_of_death_cva": boolean;
    "donor_creatinine": number;
    "donation_after_circulatory_death": boolean;
  };
  "map": {
    "systolic_bp": number;
    "diastolic_bp": number;
  };
  "meld": {
    "creatinine": number;
    "bilirubin": number;
    "inr": number;
    "sodium": number;
    "albumin": number;
    "age_at_registration": number;
    "sex"?: "male" | "female";
    "dialysis": boolean;
  };
  "mews": {
    "systolic_bp_category": "bp_le_70" | "bp_71_80" | "bp_81_100" | "bp_101_199" | "bp_ge_200";
    "heart_rate_category": "hr_le_40" | "hr_41_50" | "hr_51_100" | "hr_101_110" | "hr_111_129" | "hr_ge_130";
    "respiratory_rate_category": "rr_lt_9" | "rr_9_14" | "rr_15_20" | "rr_21_29" | "rr_ge_30";
    "temperature_category": "temp_lt_35c" | "temp_35_384c" | "temp_ge_385c";
    "avpu": "alert" | "voice" | "pain" | "unresponsive";
  };
  "morse_fall_scale": {
    "history_of_falling": "no" | "yes";
    "secondary_diagnosis": "no" | "yes";
    "ambulatory_aid": "bed_rest_nurse_assist" | "crutches_cane_walker" | "furniture";
    "iv_heparin_lock": "no" | "yes";
    "gait_transferring": "normal_bedrest_immobile" | "weak" | "impaired";
    "mental_status": "oriented_to_own_ability" | "forgets_limitations";
  };
  "neonatal_measurements": {
    "weight_grams"?: number;
    "gestational_age_weeks"?: number;
    "postnatal_age_hours"?: number;
    "corrected_gestational_age_weeks"?: number;
  };
  "nihss": {
    "assessment_timing": "baseline" | "post_treatment" | "follow_up";
    "modifier_context": "none" | "intubation" | "amputation_or_joint_fusion" | "language_barrier" | "pre_existing_deficit" | "other" | "multiple_modifiers";
    "level_of_consciousness": "alert" | "minor_stimulation" | "repeated_stimulation" | "movements_to_pain" | "unresponsive";
    "month_and_age": "both_right" | "one_right" | "none_right" | "impaired_communication" | "aphasic";
    "commands": "both_tasks" | "one_task" | "no_tasks";
    "horizontal_gaze": "normal" | "partial_overcome" | "partial_reflex" | "forced_palsy";
    "visual_fields": "no_loss" | "partial_hemianopia" | "complete_hemianopia" | "bilaterally_blind" | "bilateral_hemianopia";
    "facial_palsy": "normal" | "minor_paralysis" | "partial_paralysis" | "unilateral_complete" | "bilateral_complete";
    "left_arm_motor": "no_drift" | "drift_no_bed" | "drift_hits_bed" | "some_effort" | "no_effort" | "no_movement" | "amputation";
    "right_arm_motor": "no_drift" | "drift_no_bed" | "drift_hits_bed" | "some_effort" | "no_effort" | "no_movement" | "amputation";
    "left_leg_motor": "no_drift" | "drift_no_bed" | "drift_hits_bed" | "some_effort" | "no_effort" | "no_movement" | "amputation";
    "right_leg_motor": "no_drift" | "drift_no_bed" | "drift_hits_bed" | "some_effort" | "no_effort" | "no_movement" | "amputation";
    "limb_ataxia": "no_ataxia" | "one_limb" | "two_limbs" | "does_not_understand" | "paralyzed" | "amputation";
    "sensation": "normal" | "mild_moderate_sharp" | "mild_moderate_sense" | "complete_loss" | "quadriplegic" | "unresponsive";
    "language": "normal" | "mild_moderate" | "severe" | "mute" | "unresponsive";
    "dysarthria": "normal" | "mild_moderate" | "severe" | "mute" | "intubated";
    "extinction": "no_abnormality" | "inattention" | "extinction" | "profound_hemi_inattention" | "multiple_modalities";
  };
  "oxygenation_index": {
    "mean_airway_pressure": number;
    "fio2": number;
    "pao2"?: number;
    "spo2"?: number;
  };
  "pews": {
    "behavior": "playing_appropriate" | "sleeping" | "irritable" | "lethargic";
    "cardiovascular": "pink" | "pale" | "gray" | "gray_mottled";
    "respiratory": "normal" | "mild_distress" | "moderate_distress" | "severe_distress";
    "nebulizers": boolean;
    "vomiting": boolean;
  };
  "qsofa": {
    "respiratory_rate": number;
    "systolic_bp": number;
    "altered_mental_status": boolean;
  };
  "r_factor": {
    "alt": number;
    "alp": number;
    "alt_uln": number;
    "alp_uln": number;
  };
  "ranson": {
    "etiology_variant": "non_gallstone" | "gallstone";
    "assessment_hours": number;
    "admission_observed_at_hours": number;
    "followup_observed_at_hours"?: number;
    "age_years": number;
    "wbc_admission": number;
    "glucose_admission": number;
    "ast_admission": number;
    "ldh_admission": number;
    "hematocrit_admission": number;
    "bun_admission": number;
    "hematocrit_followup"?: number;
    "bun_followup"?: number;
    "calcium_followup"?: number;
    "pao2_followup"?: number;
    "base_deficit_followup"?: number;
    "fluid_sequestration_followup"?: number;
  };
  "sodium_deficit": {
    "weight_kg": number;
    "current_sodium": number;
    "desired_sodium": number;
    "age": number;
    "height_cm": number;
    "sex": "male" | "female";
  };
  "timi": {
    "age_65_or_older": boolean;
    "cad_risk_factors": boolean;
    "known_cad": boolean;
    "asa_use": boolean;
    "severe_angina": boolean;
    "ekg_st_changes": boolean;
    "positive_cardiac_marker": boolean;
  };
  "wells_dvt": {
    "active_cancer": boolean;
    "paralysis_or_cast": boolean;
    "bedridden": boolean;
    "localized_tenderness": boolean;
    "entire_leg_swollen": boolean;
    "calf_swelling": boolean;
    "pitting_edema": boolean;
    "collateral_veins": boolean;
    "alternative_diagnosis": boolean;
    "previously_diagnosed": boolean;
  };
}

export interface CalculatorOutputsById {
  "aa_gradient": {
    "aa_gradient": number;
    "expected_gradient": number;
  };
  "abg": {
    "sample_type": "arterial" | "peripheral_venous";
    "sample_type_provenance": "explicit" | "deprecated_flag" | "defaulted_arterial";
    "acid_base_branch_id": "within_arterial_reference" | "metabolic_acidemia" | "respiratory_acidemia" | "mixed_acidemia" | "metabolic_alkalemia" | "respiratory_alkalemia" | "mixed_alkalemia" | "compensated_or_mixed_low_values" | "compensated_or_mixed_high_values" | "indeterminate_arterial_pattern" | "screening_only_venous";
    "compensation_basis": "winters_metabolic_acidosis" | "metabolic_alkalosis_empirical" | "respiratory_compensation_not_evaluated" | "compensation_indeterminate_or_not_evaluated" | "not_applicable" | "venous_pco2_not_interchangeable";
    "expected_paco2_range"?: { low: number; high: number; mean?: number };
    "compensation_status"?: "within_expected_range" | "below_expected_range" | "above_expected_range";
    "anion_gap": number;
    "albumin_corrected_anion_gap": number;
    "albumin_provenance": "measured" | "defaulted_4_g_dl";
    "delta_ratio"?: number;
    "albumin_corrected_delta_ratio"?: number;
    "mixed_disorder_branch_ids": string[];
    "missing_data_notes": string[];
    "limitations": string[];
  };
  "anion_gap": {
    "anion_gap": number;
    "albumin_corrected_anion_gap"?: number;
    "delta_anion_gap": number;
    "albumin_corrected_delta_anion_gap"?: number;
    "delta_ratio"?: number;
    "albumin_corrected_delta_ratio"?: number;
  };
  "apgar": {
    "apgar_score": number;
  };
  "bmi": {
    "bmi": number;
  };
  "bsa": {
    "bsa": number;
  };
  "bsa_dubois": {
    "bsa": number;
  };
  "carboplatin_auc": {
    "dose": number;
    "kidney_function_absolute": number;
    "kidney_function_used": number;
    "gfr_used": number;
    "indexed_conversion_applied": boolean;
    "gfr_was_capped": boolean;
    "cap_policy_applied": "no_cap_addikd_2022" | "nci_ctep_estimated_125";
    "rounding_policy_applied": "nearest_whole_mg_addikd_2022";
  };
  "chadsvasc": {
    "score": number;
    "stroke_risk": "0.2%" | "0.6%" | "2.2%" | "3.2%" | "4.8%" | "7.2%" | "9.7%" | "11.2%" | "10.8%" | "12.2%";
    "embolism_risk": "0.3%" | "0.9%" | "2.9%" | "4.6%" | "6.7%" | "10.0%" | "13.6%" | "15.7%" | "15.2%" | "17.4%";
    "stroke_risk_percent": number;
    "thromboembolism_risk_percent": number;
    "risk_time_horizon": "one_year";
  };
  "chemo_dose_bsa": {
    "calculated_dose": number;
    "final_dose": number;
    "bsa_used": number;
    "bsa_was_capped": boolean;
    "reduction_applied": number;
  };
  "child_pugh": {
    "score": number;
    "class": "A" | "B" | "C";
    "prognosis": "Well-compensated liver disease" | "Moderately impaired liver function" | "Advanced hepatic dysfunction";
  };
  "corrected_calcium": {
    "corrected_calcium": number;
    "clinical_use_supported": boolean;
  };
  "creatinine_clearance": {
    "creatinine_clearance": number;
  };
  "csf": {
    "corrected_wbc": number;
    "wbc_correction_method": "none" | "one_wbc_per_500_rbc" | "one_wbc_per_1000_rbc" | "one_wbc_per_1500_rbc";
    "csf_serum_glucose_ratio"?: number;
    "derived_values": string[];
    "confirmed_assays": string[];
    "support_flags": string[];
    "differential_considerations": string[];
    "xanthochromia_context": "supported_spectrophotometry_after_12h" | "negative_spectrophotometry_reported" | "result_or_method_or_timing_insufficient" | "not_assessed";
    "missing_context": string[];
    "limitations": string[];
  };
  "eos": {
    "risk_at_birth_per_1000": number;
    "composite_risk_per_1000": number;
    "clinical_recommendation": "Consider starting empiric antibiotics" | "No culture, no antibiotics" | "Obtain blood culture, no empiric antibiotics" | "Empiric antibiotics" | "No additional care" | "Blood culture and vitals every 4 hours for 24 hours" | "Blood culture and vitals every 4 hours for 16 hours" | "Treat empirically with antibiotics";
    "birth_vitals_recommendation"?: "Routine vitals" | "Vitals every 4 hours for 16 hours";
    "vitals_recommendation": "Vitals per NICU" | "Routine vitals" | "Vitals every 4 hours for 24 hours" | "Vitals in NICU" | "Vitals every 4 hours for 16 hours";
  };
  "free_water_deficit": {
    "free_water_deficit": number;
    "tbw_percentage_used": number;
  };
  "gad7": {
    "gad7_score": number;
  };
  "gcs": {
    "gcs_total"?: number;
    "eye_score"?: number;
    "verbal_score"?: number;
    "motor_score"?: number;
    "assessment_complete": boolean;
    "missing_component_reasons": string[];
  };
  "gfr": {
    "gfr": number;
  };
  "gir": {
    "gir": number;
  };
  "grace": {
    "score": number;
    "mortality_risk": number;
  };
  "hepb": {
    "status_code": "acute_infection_pattern" | "chronic_infection_pattern" | "resolving_or_window_pattern" | "resolved_infection_pattern" | "vaccine_immunity_pattern" | "isolated_core_antibody_pattern" | "susceptible_pattern" | "incomplete_triple_panel" | "atypical_or_contradictory_pattern";
    "pattern_quality": "complete_supported" | "insufficient" | "contradictory_or_atypical";
    "replication_marker_context": "hbeag_detected" | "anti_hbe_detected" | "both_detected" | "neither_detected" | "not_fully_assessed";
    "missing_context": string[];
    "next_context": string[];
    "limitations": string[];
  };
  "ibw": {
    "ibw": number;
  };
  "ich_volume": {
    "volume_ml": number;
  };
  "kdpi": {
    "kdpi": number;
    "kdri_raw": number;
    "kdri_scaled": number;
    "reference_population_year": number;
    "mapping_as_of": "2026-04-03";
    "interpretation": string;
  };
  "map": {
    "map": number;
  };
  "meld": {
    "meld": number;
  };
  "mews": {
    "mews_score": number;
  };
  "morse_fall_scale": {
    "mfs_score": number;
  };
  "neonatal_measurements": {
    "uac_depth_estimate_cm"?: number;
    "uvc_depth_estimate_cm"?: number;
    "catheter_formula_id"?: "shukla_1986_original";
    "ett_depth_at_lip_cm"?: number;
    "day_one_systolic_bp_mm_hg"?: { low: number; high: number; mean?: number };
    "day_one_diastolic_bp_mm_hg"?: { low: number; high: number; mean?: number };
    "day_one_map_mm_hg"?: { low: number; high: number; mean?: number };
    "day_one_pulse_pressure_mm_hg"?: { low: number; high: number; mean?: number };
    "corrected_systolic_bp_mm_hg"?: { low: number; high: number; mean?: number };
    "corrected_diastolic_bp_mm_hg"?: { low: number; high: number; mean?: number };
    "corrected_map_mm_hg"?: { low: number; high: number; mean?: number };
    "corrected_pulse_pressure_mm_hg"?: { low: number; high: number; mean?: number };
    "limitations": string[];
  };
  "nihss": {
    "nihss_score"?: number;
    "assessment_complete": boolean;
    "missing_component_reasons": string[];
  };
  "oxygenation_index": {
    "oi"?: number;
    "osi"?: number;
  };
  "pews": {
    "pews_score": number;
  };
  "qsofa": {
    "score": number;
  };
  "r_factor": {
    "r_factor": number;
    "injury_type": "Hepatocellular" | "Mixed" | "Cholestatic";
  };
  "ranson": {
    "admission_subtotal": number;
    "admission_complete": boolean;
    "score"?: number;
    "historical_mortality_band"?: "~1%" | "~15%" | "~40%" | "~100%";
    "assessment_complete": boolean;
    "missing_component_reasons": string[];
    "criterion_provenance": CriterionProvenance[];
  };
  "sodium_deficit": {
    "sodium_deficit": number;
    "total_body_water": number;
  };
  "timi": {
    "score": number;
    "risk_percentage": "4.7%" | "8.3%" | "13.2%" | "19.9%" | "26.2%" | "40.9%";
    "risk_percent": number;
    "risk_horizon_days": number;
    "risk_endpoint": "death_mi_or_urgent_revascularization";
  };
  "wells_dvt": {
    "score": number;
    "risk_category": "likely" | "unlikely";
  };
}

export type ComputeValue =
  | number | string | boolean | string[] | number[]
  | { low: number; high: number; mean?: number } | CriterionProvenance[];
